import {createHash} from "node:crypto";
import {NextRequest,NextResponse} from "next/server";
import {requireApiUser} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";

export const runtime="nodejs";
type Row=Record<string,string>;
function parseCsv(text:string):Row[]{const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell="";}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)return[];const headers=rows[0].map(h=>h.trim().replace(/^\uFEFF/,""));return rows.slice(1).map(values=>Object.fromEntries(headers.map((h,i)=>[h,(values[i]||"").trim()])));}
function pick(row:Row,...names:string[]){for(const name of names){const key=Object.keys(row).find(k=>k.toLowerCase()===name.toLowerCase());if(key&&row[key])return row[key];}return"";}
function iso(value:string){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();}
function id(parts:string[]){return createHash("sha256").update(parts.join("\u001f")).digest("hex");}
function direction(row:Row){const value=`${pick(row,"Type")} ${pick(row,"Direction")} ${pick(row,"Status")}`.toLowerCase();return /(outgoing|outbound|sent|delivered)/.test(value)?"outbound":"inbound";}
function messageRows(rows:Row[],owner_id:string,workspace_id:string,profile_id:string){return rows.map(row=>{const date=iso(pick(row,"Message Date","Sent Date","Date"));if(!date)return null;const chat=pick(row,"Chat Session","Conversation","Thread");const sender=pick(row,"Sender Name","Sender ID","Sender","From")||chat||"Message";const text=pick(row,"Text","Message","Body");const service=pick(row,"Service")||"iMessage/SMS";const external=id(["message",chat,date,sender,text,pick(row,"Attachment")]);return{owner_id,workspace_id,profile_id,connection_id:null,provider:"iphone",external_id:external,thread_external_id:chat||sender,channel:"sms",direction:direction(row),subject:chat||null,sender,recipients:chat?[chat]:[],preview:text.slice(0,220)||service,body_text:text||null,occurred_at:date,raw_metadata:{source:"iphone_csv",service,type:pick(row,"Type"),status:pick(row,"Status"),attachment:pick(row,"Attachment"),attachment_type:pick(row,"Attachment type")}}}).filter(Boolean);}
function callRows(rows:Row[],owner_id:string,workspace_id:string,profile_id:string){return rows.map(row=>{const date=iso(pick(row,"Date","Call Date","Start Date","Timestamp"));if(!date)return null;const name=pick(row,"Name","Contact","Contact Name","Caller Name");const number=pick(row,"Number","Phone Number","Address","Caller ID");const dir=pick(row,"Direction","Type")||"Call";const duration=pick(row,"Duration","Call Duration");const external=id(["call",date,name,number,dir,duration]);return{owner_id,workspace_id,profile_id,connection_id:null,provider:"iphone",external_id:external,thread_external_id:number||name||external,channel:"call",direction:/outgoing|outbound/i.test(dir)?"outbound":"inbound",subject:`${dir}${duration?` · ${duration}`:""}`,sender:name||number||"Phone call",recipients:number?[number]:[],preview:[dir,duration&&`${duration} duration`,number].filter(Boolean).join(" · "),body_text:null,occurred_at:date,raw_metadata:{source:"iphone_csv",direction:dir,duration,number,name,service:pick(row,"Service","Call Type")}}}).filter(Boolean);}
export async function POST(request:NextRequest){try{const user=await requireApiUser();const form=await request.formData();const files=form.getAll("files").filter((v):v is File=>v instanceof File);if(!files.length)return NextResponse.json({error:"Choose at least one CSV file."},{status:400});if(files.length>10||files.some(f=>f.size>15_000_000))return NextResponse.json({error:"Use up to 10 CSV files, 15 MB each."},{status:400});const admin=createAdminClient();const{data:profile}=await admin.from("profiles").select("id,personal_workspace_id").eq("owner_id",user.id).eq("kind","personal").single();if(!profile)return NextResponse.json({error:"Profile not found."},{status:404});let candidates:any[]=[];for(const file of files){const rows=parseCsv(await file.text());if(!rows.length)continue;const headers=Object.keys(rows[0]).map(h=>h.toLowerCase());const isMessages=headers.includes("message date")||headers.includes("chat session")||headers.includes("sender id");const isCalls=headers.includes("duration")&&(headers.includes("direction")||headers.includes("number")||headers.includes("phone number"));if(isMessages)candidates.push(...messageRows(rows,user.id,profile.personal_workspace_id,profile.id));else if(isCalls)candidates.push(...callRows(rows,user.id,profile.personal_workspace_id,profile.id));}if(!candidates.length)return NextResponse.json({error:"Compass could not recognize these CSV files as Messages or Call History exports."},{status:400});candidates=candidates.slice(0,10000);const ids=candidates.map(x=>x.external_id);const existing=new Set<string>();for(let i=0;i<ids.length;i+=500){const{data}=await admin.from("communication_items").select("external_id").eq("owner_id",user.id).eq("provider","iphone").in("external_id",ids.slice(i,i+500));for(const item of data||[])existing.add(item.external_id);}const fresh=candidates.filter(x=>!existing.has(x.external_id));let imported=0;for(let i=0;i<fresh.length;i+=500){const{error}=await admin.from("communication_items").insert(fresh.slice(i,i+500));if(error){console.error("Phone CSV import failed",error);return NextResponse.json({error:"Compass could not save the phone import."},{status:500});}imported+=Math.min(500,fresh.length-i);}return NextResponse.json({imported,skipped:candidates.length-fresh.length});}catch(error){const message=error instanceof Error?error.message:"";if(message==="UNAUTHORIZED")return NextResponse.json({error:"Sign in again to import phone data."},{status:401});console.error("Phone import failed",error);return NextResponse.json({error:"Phone import failed."},{status:500});}}
