import Link from "next/link";
import {requireUser} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";
import {ConnectAccountButtons} from "@/components/connect-account-buttons";
import {PhoneImport} from "@/components/phone-import";
import {SettingsNav} from "@/components/settings-nav";
export const dynamic="force-dynamic";
type ConnectionRow={id:string;provider:"google"|"microsoft";account_email:string;display_name:string|null;status:string};
function first(value:string|string[]|undefined){return Array.isArray(value)?value[0]||null:value||null}
export default async function ConnectionsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const user=await requireUser();const admin=createAdminClient();const params=await searchParams;const[{data:profile},{data:connections},{count:phoneCount}]=await Promise.all([admin.from("profiles").select("id").eq("owner_id",user.id).eq("kind","personal").single(),admin.from("provider_connections").select("id,provider,account_email,display_name,status").eq("owner_id",user.id).order("created_at"),admin.from("communication_items").select("id",{count:"exact",head:true}).eq("owner_id",user.id).eq("provider","iphone")]);const rows=(connections||[]) as ConnectionRow[];const connected=first(params.connected);return <div className="settings-layout"><SettingsNav active="connections"/><div className="content-stack"><section className="card page-intro"><div><p className="eyebrow">Connections</p><h1>Your accounts & phone</h1><p className="muted">Connect the things you want Compass to bring together. Technical details stay out of the way.</p></div>{profile&&<ConnectAccountButtons profileId={profile.id}/>}</section>{connected&&<div className="notice success">Account connected.</div>}<section className="provider-control-grid"><SimpleProvider title="Gmail" icon="G" rows={rows.filter(r=>r.provider==="google")} href="/app/messages?source=gmail"/><SimpleProvider title="Outlook" icon="O" rows={rows.filter(r=>r.provider==="microsoft")} href="/app/messages?source=outlook"/></section><section className="card"><div className="section-heading"><div><p className="eyebrow">iPhone</p><h2>Texts & calls</h2><p className="muted">Bring your iPhone message and call history into Compass. Imported items appear automatically under Texts and Calls.</p></div><span className="pill">{phoneCount||0} imported</span></div><PhoneImport/><div className="phone-help"><b>What to export</b><p>On a Windows PC or Mac, export Messages as CSV and Call History as CSV from an iPhone backup tool. Select both files above and Compass will combine them with your email while keeping Texts and Calls separate.</p></div></section><section className="card"><div className="section-heading"><div><h2>Privacy</h2><p className="muted">Only connect or import information you want inside Compass. Your account connection controls and imports live here so Home and Messages stay simple.</p></div></div></section></div></div>}
function SimpleProvider({title,icon,rows,href}:{title:string;icon:string;rows:ConnectionRow[];href:string}){return <section className="card provider-control-card"><div className="provider-control-heading"><span className="provider-icon">{icon}</span><div><h2>{title}</h2><small>{rows.length?`${rows.length} connected`:"Not connected"}</small></div></div>{rows.length?<div className="provider-account-list">{rows.map(row=><div className="provider-account-row" key={row.id}><div><b>{row.account_email}</b><small>{row.display_name||title}</small></div><Link className="button secondary" href={`${href}&account=${row.id}`}>Open</Link></div>)}</div>:<p className="muted">Use Connect Google or Connect Microsoft above.</p>}</section>}
