"use client";
import {useEffect,useState} from "react";
import styles from "./appearance-settings.module.css";
import {defaultAppearance,type AppearanceProfile,type ThemeMode} from "@/lib/personalization";
const groups:Array<{title:string;note:string;key:keyof AppearanceProfile;options:Array<[string,string]>}>=[
{title:"Theme",note:"Base color mode",key:"mode",options:[["system","System"],["light","Light"],["dark","Dark"]]},
{title:"Accent",note:"Primary interface color",key:"accent",options:[["violet","Violet"],["blue","Blue"],["cyan","Cyan"],["green","Green"],["gold","Gold"],["orange","Orange"],["rose","Rose"],["red","Red"],["graphite","Graphite"]]},
{title:"Workspace width",note:"Control how much of the screen Compass uses",key:"workspaceWidth",options:[["focused","Focused"],["standard","Standard"],["wide","Wide"],["fluid","Full width"]]},
{title:"Spacing",note:"Set the distance between sections",key:"spacing",options:[["tight","Tight"],["standard","Standard"],["airy","Airy"]]},
{title:"Density",note:"Control information density",key:"density",options:[["compact","Compact"],["comfortable","Comfortable"],["spacious","Spacious"]]},
{title:"Corners",note:"Shape cards and controls",key:"radius",options:[["square","Square"],["soft","Soft"],["round","Round"],["pill","Pill"]]},
{title:"Surface",note:"Choose the material of panels",key:"surface",options:[["solid","Solid"],["glass","Glass"],["paper","Paper"],["midnight","Midnight"]]},
{title:"Elevation",note:"Control card depth and shadows",key:"elevation",options:[["flat","Flat"],["soft","Soft"],["raised","Raised"]]},
{title:"Text scale",note:"Change interface reading size",key:"scale",options:[["small","Small"],["normal","Normal"],["large","Large"]]},
{title:"Navigation",note:"Choose sidebar presentation",key:"navMode",options:[["expanded","Expanded"],["compact","Compact"],["icons","Icons"]]},
{title:"Header",note:"Choose how the top bar behaves",key:"headerMode",options:[["sticky","Sticky"],["static","Scrolls"],["hidden","Hidden"]]},
{title:"Interface",note:"Control visual prominence",key:"chrome",options:[["minimal","Minimal"],["balanced","Balanced"],["expressive","Expressive"]]},
{title:"Background",note:"Set the workspace atmosphere",key:"background",options:[["calm","Calm"],["gradient","Gradient"],["graphite","Graphite"],["warm","Warm"],["ocean","Ocean"]]},
{title:"Motion",note:"Tune interface movement",key:"motion",options:[["full","Full"],["reduced","Reduced"],["none","None"]]}
];
function resolvedTheme(mode:ThemeMode):"light"|"dark"{return mode!=="system"?mode:window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";}
export function applyAppearance(p:AppearanceProfile){const r=document.documentElement;r.dataset.themeMode=p.mode;r.dataset.theme=resolvedTheme(p.mode);r.dataset.accent=p.accent;r.dataset.density=p.density;r.dataset.radius=p.radius;r.dataset.surface=p.surface;r.dataset.motion=p.motion;r.dataset.scale=p.scale;r.dataset.navMode=p.navMode;r.dataset.chrome=p.chrome;r.dataset.background=p.background;r.dataset.workspaceWidth=p.workspaceWidth;r.dataset.spacing=p.spacing;r.dataset.elevation=p.elevation;r.dataset.headerMode=p.headerMode;r.dataset.reducedTransparency=String(p.reducedTransparency);r.dataset.showHelperText=String(p.showHelperText);r.dataset.showTimestamps=String(p.showTimestamps);localStorage.setItem("compass-appearance",JSON.stringify(p));}
export function AppearanceSettings({initialAppearance}:{initialAppearance:AppearanceProfile}){const[a,setA]=useState(initialAppearance||defaultAppearance);const[status,setStatus]=useState("");useEffect(()=>applyAppearance(a),[a]);async function save(next:AppearanceProfile){applyAppearance(next);setA(next);setStatus("Saving…");try{const res=await fetch("/api/settings/appearance",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!res.ok)throw new Error();setStatus("Saved to your profile");}catch{setStatus("Applied here; profile save needs attention");}}function patch(key:keyof AppearanceProfile,value:AppearanceProfile[keyof AppearanceProfile]){void save({...a,[key]:value});}return <div className={styles.studio}><section className={`${styles.hero} card`} data-no-layout-edit><div><p className="eyebrow">Personal Studio</p><h2>Your interface, not a fixed dashboard.</h2><p>Change the shell, workspace width, spacing, cards, navigation, typography, motion and information detail. Use Customize in the top bar to move, resize or remove sections on individual pages.</p></div><button className={styles.reset} onClick={()=>void save(defaultAppearance)}>Reset everything</button></section><div className={styles.grid}>{groups.map(g=><section className={`${styles.section} card`} key={g.title}><div className={styles.sectionHeader}><div><p className="eyebrow">Interface</p><h3>{g.title}</h3><p>{g.note}</p></div><span className="pill">{String(a[g.key])}</span></div><div className={styles.options}>{g.options.map(([id,label])=><button type="button" key={id} className={`${styles.option}${a[g.key]===id?` ${styles.selected}`:""}`} onClick={()=>patch(g.key,id as AppearanceProfile[typeof g.key])}><b>{label}</b></button>)}</div></section>)}</div><section className={`${styles.section} card`}><div className={styles.sectionHeader}><div><p className="eyebrow">Details</p><h3>Information & accessibility</h3><p>Choose how much secondary interface detail Compass shows.</p></div></div><div className={styles.options}>{([["reducedTransparency","Reduce transparency"],["showHelperText","Show helper text"],["showTimestamps","Show timestamps"]] as Array<["reducedTransparency"|"showHelperText"|"showTimestamps",string]>).map(([key,label])=><button type="button" key={key} className={`${styles.option}${a[key]?` ${styles.selected}`:""}`} onClick={()=>patch(key,!a[key])}><b>{label}</b><small>{a[key]?"On":"Off"}</small></button>)}</div></section>{status&&<p className={styles.status}>{status}</p>}</div>}
export type {ThemeMode,AppearanceProfile};
