"use client";
import {useEffect,useState} from "react";
import styles from "./appearance-settings.module.css";
import {defaultAppearance,type AppearanceProfile,type ThemeMode} from "@/lib/personalization";
const presets:Array<{name:string;note:string;emoji:string;value:Partial<AppearanceProfile>}>= [
{name:"iOS Light",note:"Bright, clean and familiar",emoji:"◯",value:{mode:"light",accent:"blue",surface:"glass",background:"calm",radius:"round",elevation:"soft",chrome:"minimal",density:"comfortable",spacing:"standard"}},
{name:"Midnight",note:"Deep dark interface",emoji:"●",value:{mode:"dark",accent:"blue",surface:"midnight",background:"graphite",radius:"round",elevation:"flat",chrome:"minimal"}},
{name:"Purple Glass",note:"Soft translucent violet",emoji:"✦",value:{mode:"light",accent:"violet",surface:"glass",background:"gradient",radius:"round",elevation:"soft",chrome:"expressive"}},
{name:"Ocean",note:"Cool blue and cyan",emoji:"≈",value:{mode:"light",accent:"cyan",surface:"glass",background:"ocean",radius:"round",elevation:"soft"}},
{name:"Warm Home",note:"Relaxed warm neutral",emoji:"⌂",value:{mode:"light",accent:"orange",surface:"paper",background:"warm",radius:"round",elevation:"soft",chrome:"minimal"}},
{name:"Rose",note:"Soft pink personal theme",emoji:"♡",value:{mode:"light",accent:"rose",surface:"glass",background:"gradient",radius:"pill",elevation:"soft"}},
{name:"Graphite",note:"Neutral and understated",emoji:"◆",value:{mode:"light",accent:"graphite",surface:"solid",background:"graphite",radius:"soft",elevation:"flat",chrome:"minimal"}},
{name:"Night Violet",note:"Dark with violet highlights",emoji:"☾",value:{mode:"dark",accent:"violet",surface:"glass",background:"graphite",radius:"round",elevation:"raised",chrome:"expressive"}},
{name:"Fresh",note:"Bright green and airy",emoji:"◇",value:{mode:"light",accent:"green",surface:"solid",background:"calm",radius:"round",elevation:"soft",density:"spacious",spacing:"airy"}},
{name:"Sunset",note:"Warm orange and rose",emoji:"◒",value:{mode:"light",accent:"rose",surface:"paper",background:"warm",radius:"round",elevation:"raised",chrome:"expressive"}},
{name:"Minimal",note:"Almost no visual chrome",emoji:"—",value:{mode:"system",accent:"graphite",surface:"solid",background:"calm",radius:"soft",elevation:"flat",chrome:"minimal",density:"compact",spacing:"tight"}},
{name:"Big & Easy",note:"Large text and roomy controls",emoji:"A",value:{mode:"system",accent:"blue",surface:"solid",background:"calm",radius:"pill",elevation:"soft",scale:"large",density:"spacious",spacing:"airy"}}
];
const groups:Array<{title:string;note:string;key:keyof AppearanceProfile;options:Array<[string,string]>}>=[
{title:"Light & dark",note:"Match your device or choose a mode",key:"mode",options:[["system","Automatic"],["light","Light"],["dark","Dark"]]},
{title:"Color",note:"Pick the main color used throughout Compass",key:"accent",options:[["violet","Violet"],["blue","Blue"],["cyan","Aqua"],["green","Green"],["gold","Gold"],["orange","Orange"],["rose","Pink"],["red","Red"],["graphite","Gray"]]},
{title:"Cards",note:"Choose how screens and panels feel",key:"surface",options:[["solid","Clean"],["glass","Glass"],["paper","Soft"],["midnight","Midnight"]]},
{title:"Background",note:"Change the overall atmosphere",key:"background",options:[["calm","Simple"],["gradient","Color wash"],["graphite","Gray"],["warm","Warm"],["ocean","Ocean"]]},
{title:"Corners",note:"Change the shape of cards and buttons",key:"radius",options:[["square","Square"],["soft","Soft"],["round","Round"],["pill","Extra round"]]},
{title:"Text size",note:"Adjust reading size",key:"scale",options:[["small","Small"],["normal","Standard"],["large","Large"]]},
{title:"Roominess",note:"Choose how much fits on screen",key:"density",options:[["compact","More"],["comfortable","Standard"],["spacious","Roomy"]]},
{title:"Page width",note:"Choose how wide content can spread",key:"workspaceWidth",options:[["focused","Narrow"],["standard","Standard"],["wide","Wide"],["fluid","Full screen"]]},
{title:"Section spacing",note:"Adjust space between groups",key:"spacing",options:[["tight","Tight"],["standard","Standard"],["airy","Airy"]]},
{title:"Depth",note:"Change shadows around cards",key:"elevation",options:[["flat","Flat"],["soft","Soft"],["raised","Floating"]]},
{title:"Side menu",note:"Choose how much navigation is visible",key:"navMode",options:[["expanded","Names & icons"],["compact","Compact"],["icons","Icons only"]]},
{title:"Top bar",note:"Choose how the top bar behaves",key:"headerMode",options:[["sticky","Always visible"],["static","Scroll away"],["hidden","Hidden"]]},
{title:"Visual style",note:"Adjust overall visual emphasis",key:"chrome",options:[["minimal","Minimal"],["balanced","Balanced"],["expressive","Expressive"]]},
{title:"Animation",note:"Choose how much movement you see",key:"motion",options:[["full","Smooth"],["reduced","Reduced"],["none","None"]]}
];
function resolvedTheme(mode:ThemeMode):"light"|"dark"{return mode!=="system"?mode:window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";}
export function applyAppearance(p:AppearanceProfile){const r=document.documentElement;r.dataset.themeMode=p.mode;r.dataset.theme=resolvedTheme(p.mode);r.dataset.accent=p.accent;r.dataset.density=p.density;r.dataset.radius=p.radius;r.dataset.surface=p.surface;r.dataset.motion=p.motion;r.dataset.scale=p.scale;r.dataset.navMode=p.navMode;r.dataset.chrome=p.chrome;r.dataset.background=p.background;r.dataset.workspaceWidth=p.workspaceWidth;r.dataset.spacing=p.spacing;r.dataset.elevation=p.elevation;r.dataset.headerMode=p.headerMode;r.dataset.reducedTransparency=String(p.reducedTransparency);r.dataset.showHelperText=String(p.showHelperText);r.dataset.showTimestamps=String(p.showTimestamps);localStorage.setItem("compass-appearance",JSON.stringify(p));}
export function AppearanceSettings({initialAppearance}:{initialAppearance:AppearanceProfile}){const[a,setA]=useState(initialAppearance||defaultAppearance);const[status,setStatus]=useState("");useEffect(()=>applyAppearance(a),[a]);async function save(next:AppearanceProfile){applyAppearance(next);setA(next);setStatus("Saving…");try{const res=await fetch("/api/settings/appearance",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!res.ok)throw new Error();setStatus("Saved");}catch{setStatus("Applied on this device");}}function patch(key:keyof AppearanceProfile,value:AppearanceProfile[keyof AppearanceProfile]){void save({...a,[key]:value});}return <div className={styles.studio}><section className={`${styles.hero} card`} data-no-layout-edit><div><p className="eyebrow">Appearance</p><h2>Make Compass feel like yours.</h2><p>Start with a look you like, then change as much or as little as you want.</p></div><button className={styles.reset} onClick={()=>void save(defaultAppearance)}>Reset</button></section><section className={`${styles.section} card`}><div className={styles.sectionHeader}><div><p className="eyebrow">Themes</p><h3>Choose a look</h3><p>One tap changes the whole interface. You can fine-tune it below.</p></div></div><div className={styles.options}>{presets.map(p=><button type="button" key={p.name} className={styles.option} onClick={()=>void save({...a,...p.value})}><b>{p.emoji} {p.name}</b><small>{p.note}</small></button>)}</div></section><div className={styles.grid}>{groups.map(g=><section className={`${styles.section} card`} key={g.title}><div className={styles.sectionHeader}><div><h3>{g.title}</h3><p>{g.note}</p></div></div><div className={styles.options}>{g.options.map(([id,label])=><button type="button" key={id} className={`${styles.option}${a[g.key]===id?` ${styles.selected}`:""}`} onClick={()=>patch(g.key,id as AppearanceProfile[typeof g.key])}><b>{label}</b></button>)}</div></section>)}</div><section className={`${styles.section} card`}><div className={styles.sectionHeader}><div><h3>Display options</h3><p>Extra controls are kept here instead of cluttering the rest of Compass.</p></div></div><div className={styles.options}>{([["reducedTransparency","Reduce transparency"],["showHelperText","Show helpful descriptions"],["showTimestamps","Show dates & times"]] as Array<["reducedTransparency"|"showHelperText"|"showTimestamps",string]>).map(([key,label])=><button type="button" key={key} className={`${styles.option}${a[key]?` ${styles.selected}`:""}`} onClick={()=>patch(key,!a[key])}><b>{label}</b><small>{a[key]?"On":"Off"}</small></button>)}</div></section>{status&&<p className={styles.status}>{status}</p>}</div>}
export type {ThemeMode,AppearanceProfile};
